spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://146.56.102.131:3306/importKeeper?useSSL=false&characterEncoding=UTF-8
    username: importKeeper
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8080